# Generated by Django 4.0 on 2021-12-17 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('authentication', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.IntegerField()),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', unique=True)),
                ('event_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract', unique=True)),
                ('support_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user', unique=True)),
            ],
        ),
    ]
