# Generated by Django 4.0 on 2022-01-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_contract_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(unique=True, verbose_name="Contract's status"),
        ),
    ]
