# Generated by Django 4.0 on 2022-01-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(verbose_name="Contract's status"),
        ),
    ]
